/**
 * Canonical tree → Markdown + structuredContent.
 *
 * The citation footer is the contract surface between Truth 6 (in the plan),
 * the TS-005 test, and this serializer. It is defined ONCE here as named
 * constants and re-used by tests so the three places stay byte-identical.
 */

import { CanonicalNode } from './canonical_tree.js';
import { Citation, SerializerError } from '../types.js';
import { estimateTokens, renderNode } from './render_internals.js';

/**
 * Footer template — substitute `${sourceUrl}` and `${commitSha}` at emit time.
 * Truth 6 + TS-005 must regex-match the rendered version of this template.
 */
export const CITATION_FOOTER_TEMPLATE =
  '\n\n---\n*Source: ${sourceUrl} — content generated by Google CodeWiki (Gemini), pinned to commit ${commitSha}. AI-generated, verify against source.*';

/**
 * Canonical regex used by tests and verification to confirm the footer is present.
 */
export const CITATION_FOOTER_REGEX =
  /\n---\n\*Source: (https:\/\/codewiki\.google\/github\.com\/[^\s]+) — content generated by Google CodeWiki \(Gemini\), pinned to commit ([0-9a-f]{40})\. AI-generated, verify against source\.\*$/;

/**
 * PSF-004 layer 3: SHA validator for citation footers. The
 * CITATION_FOOTER_REGEX requires `[0-9a-f]{40}`; anything else would
 * render a broken footer that fails the byte-equal contract. The
 * serializer throws BEFORE constructing the footer string so no broken
 * bytes ever reach stdout. The indexer (layer 1) and retriever (layer 2)
 * also defend against this case upstream, but this is the load-bearing
 * guard — any future caller that bypasses the upstream layers still
 * cannot emit a broken footer.
 */
const COMMIT_SHA_PATTERN = /^[0-9a-f]{40}$/;

function assertValidCommitSha(commitSha: string): void {
  if (!COMMIT_SHA_PATTERN.test(commitSha)) {
    throw new SerializerError(
      'invalid_commit_sha',
      `serializer: citation.commitSha must be a 40-character hex SHA, got ${JSON.stringify(commitSha)}`,
    );
  }
}

export interface SerializeOptions {
  maxTokens: number;
}

export interface SerializeResult {
  markdown: string;
  structuredContent: { nodes: CanonicalNode[] };
  truncated: boolean;
}

function renderFooter(citation: Citation): string {
  assertValidCommitSha(citation.commitSha);
  return CITATION_FOOTER_TEMPLATE
    .replace('${sourceUrl}', citation.sourceUrl)
    .replace('${commitSha}', citation.commitSha);
}

export function serialize(
  nodes: CanonicalNode[],
  citation: Citation,
  opts: SerializeOptions,
): SerializeResult {
  // Validate upfront so an empty/malformed SHA fails fast — before any
  // chunk text is rendered, before any stdout-bound bytes accumulate.
  assertValidCommitSha(citation.commitSha);
  const pieces: string[] = [];
  let truncated = false;
  let runningTokens = 0;

  for (const n of nodes) {
    const piece = renderNode(n);
    const pieceTokens = estimateTokens(piece);
    if (runningTokens + pieceTokens > opts.maxTokens) {
      truncated = true;
      // Deterministic UX: when the first node alone exceeds the budget,
      // still emit it so the consumer has a recognizable starting point
      // alongside the truncation notice. Otherwise get_page collapses to
      // just "_Truncated_" + footer with an empty body.
      if (pieces.length === 0) {
        pieces.push(piece);
      }
      break;
    }
    pieces.push(piece);
    runningTokens += pieceTokens;
  }

  let markdown = pieces.join('\n').trimEnd();

  if (truncated) {
    markdown += '\n\n_Truncated to fit token budget._';
  }

  markdown += renderFooter(citation);

  return {
    markdown,
    structuredContent: { nodes },
    truncated,
  };
}
