/**
 * Construct the MCP server with all 5 tools wired up.
 *
 * The `instructions:` field is the agent's first-touch guidance — it tells
 * the model when to call which tool. Keep it tight to stay under Anthropic's
 * 10%-of-context tool-surface threshold.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

import { Cache } from './services/cache.js';
import { CodeWikiClient, getCodeWikiClient } from './services/codewiki_client.js';
import { Embedder, getEmbedder } from './adapters/embedder.js';
import { Reranker, getReranker } from './adapters/reranker.js';
import { VectorStore } from './services/vector_store.js';
import { GraphStore } from './services/graph_store.js';
import { Indexer } from './services/indexer.js';
import { Retriever } from './services/retriever.js';
import { GraphQuery } from './services/graph_query.js';
import { registerListProjectDependencies } from './tools/list_project_dependencies.js';
import { registerResolveRepo } from './tools/resolve_repo.js';
import { registerGetPage } from './tools/get_page.js';
import { registerFindChunks } from './tools/find_chunks.js';
import { registerFindNeighbors } from './tools/find_neighbors.js';
import type { ProjectScan } from './types.js';

/**
 * v2.1 KG rollback escape hatch. When `CODEWIKI_DISABLE_KG=1`, `find_neighbors`
 * is NOT registered AND the indexer coerces `buildGraph: false` regardless of
 * caller opts. Read once at module load — restart-required to toggle.
 */
const KG_DISABLED = process.env.CODEWIKI_DISABLE_KG === '1';

/**
 * Server version derived from `package.json` at module load (PSF-001 fix).
 * Previously a hardcoded literal here drifted from `package.json.version`,
 * so the MCP server advertised a different version to clients than the
 * npm-installed binary actually was. The runtime read keeps both surfaces
 * synchronized automatically.
 *
 * The resolved path: in dev (tsx) the module is `src/server.ts`, so
 * `../package.json` resolves to the project root. After `tsc` build the
 * module is `dist/server.js`, and `../package.json` again resolves to the
 * project root (since `dist/` is one level below the root).
 */
function loadServerVersion(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const pkgPath = path.resolve(here, '..', 'package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')) as { version?: string };
  if (!pkg.version) {
    throw new Error(`server.ts: failed to read version from ${pkgPath}`);
  }
  return pkg.version;
}

export const SERVER_VERSION = loadServerVersion();

export const SERVER_INSTRUCTIONS =
  'Decide tool by question:\n' +
  '- "What does this project use?" -> list_project_dependencies.\n' +
  '- "Which github repo is package X?" -> resolve_repo.\n' +
  '- "How does X work / where is Y?" -> find_chunks (auto-indexes on first call; do NOT pre-warm unless you have already hit a slow first response).\n' +
  '- "Show me this page / section" -> get_page (set listPages:true for the page index; subsection drills into a heading).\n' +
  '- "What pages connect to this code / section?" -> find_neighbors (after find_chunks gave you a chunk).\n' +
  "- Pre-warm an index only if a prior find_chunks returned status:'index_building' AND you need a guaranteed cache hit: get_page({ repo, prepareOnly: true }).\n" +
  'Always surface citation.sourceUrl. Content is AI-generated by Google CodeWiki — verify against the source repository.';

export interface BuildServerOptions {
  cwd: string;
  cache?: Cache;
  client?: CodeWikiClient;
  /** Optional v2 RAG dependencies. Tests inject mocks; production uses defaults. */
  embedder?: Embedder;
  /** v2.6: cross-encoder reranker. Tests inject mocks; production uses the singleton. */
  reranker?: Reranker;
  retriever?: Retriever;
  /** Optional v2.1 KG dependencies. */
  graphQuery?: GraphQuery;
  /** Optional callback returning the project scan, used by find_neighbors `cross_repo` for dep_link derivation. */
  getProjectDeps?: () => ProjectScan;
}

export interface BuiltServer {
  server: McpServer;
  cache: Cache;
  client: CodeWikiClient;
  retriever: Retriever;
  graphQuery: GraphQuery;
  /** Surfaced so the get_page prepareOnly path wires onto the SAME Indexer instance the tools use (single-flight collapse). */
  indexer: Indexer;
  /** v3 (MCP -32000 fix RC1 L3): surfaced for the boot-time warmupModels() background call in src/index.ts:main(). */
  embedder: Embedder;
  /** v3 (MCP -32000 fix RC1 L3): surfaced for the boot-time warmupModels() background call in src/index.ts:main(). */
  reranker: Reranker;
  toolNames: string[];
}

export async function buildServer(opts: BuildServerOptions): Promise<BuiltServer> {
  const cache = opts.cache ?? (await Cache.open());
  const client = opts.client ?? (await getCodeWikiClient());

  // v2 RAG wiring — lazy: embedder is only loaded when find_chunks is called.
  const embedder = opts.embedder ?? (await getEmbedder());
  // v2.6: reranker singleton (also lazy — model load fires on first score()).
  const reranker = opts.reranker ?? (await getReranker());
  const store = new VectorStore(cache);
  const graphStore = new GraphStore(cache);
  const indexer = new Indexer({ client, embedder, store, graphStore, cache });
  const retriever = opts.retriever ?? new Retriever({ embedder, reranker, store, indexer, cache });
  // v2.5: pass embedder so find_neighbors can lazy-load it for the
  // optional `query` semantic-rank branch. The embedder constructor is
  // free; the encode() lazy-load only fires when query is actually set.
  const graphQuery = opts.graphQuery ?? new GraphQuery({ graphStore, vectorStore: store, cache, indexer, embedder });

  const server = new McpServer(
    { name: 'codewiki-mcp', version: SERVER_VERSION },
    { capabilities: { logging: {} }, instructions: SERVER_INSTRUCTIONS },
  );

  registerListProjectDependencies(server, { cache, client, cwd: opts.cwd });
  registerResolveRepo(server, { cache });
  // v0.7: get_page is now the only non-readonly tool — `prepareOnly: true`
  // (the v0.6 request_indexing replacement) triggers an HTTP fetch + sqlite
  // write. Annotations on the tool reflect this; `idempotentHint: true`
  // remains thanks to the Indexer's single-flight + TTL contract.
  registerGetPage(server, { client, indexer });
  registerFindChunks(server, { retriever });

  // v2.1 KG: register find_neighbors unless the rollback flag is set.
  if (!KG_DISABLED) {
    registerFindNeighbors(server, { graphQuery, getProjectDeps: opts.getProjectDeps });
  }

  // v0.7: Tool surface locked at 5 names (4 when KG disabled). The Cloudmeru-
  // parity regex `/search|ask|query|generate|index|write/i` in
  // tests/unit/server.test.ts rejects every match-token now — the empty
  // FORBIDDEN_TOKEN_WHITELIST is the new lock. list_pages is exposed via
  // get_page({ listPages: true }); pre-warm via get_page({ prepareOnly: true }).
  const toolNames = [
    'list_project_dependencies',
    'resolve_repo',
    'get_page',
    'find_chunks',
    ...(KG_DISABLED ? [] : ['find_neighbors']),
  ];
  return { server, cache, client, retriever, graphQuery, indexer, embedder, reranker, toolNames };
}
