/**
 * Construct the MCP server with all 7 tools wired up.
 *
 * The `instructions:` field is the agent's first-touch guidance — it tells
 * the model when to call which tool. Keep it tight (≤ 240 chars per claim)
 * to stay under Anthropic's 10%-of-context tool-surface threshold.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

import { Cache } from './services/cache.js';
import { CodeWikiClient, getCodeWikiClient } from './services/codewiki_client.js';
import { Embedder, getEmbedder } from './adapters/embedder.js';
import { Reranker, getReranker } from './adapters/reranker.js';
import { VectorStore } from './services/vector_store.js';
import { GraphStore } from './services/graph_store.js';
import { Indexer } from './services/indexer.js';
import { Retriever } from './services/retriever.js';
import { GraphQuery } from './services/graph_query.js';
import { registerListProjectDependencies } from './tools/list_project_dependencies.js';
import { registerResolveRepo } from './tools/resolve_repo.js';
import { registerListPages } from './tools/list_pages.js';
import { registerGetPage } from './tools/get_page.js';
import { registerFindChunks } from './tools/find_chunks.js';
import { registerFindNeighbors } from './tools/find_neighbors.js';
import { registerRequestIndexing } from './tools/request_indexing.js';
import type { ProjectScan } from './types.js';

/**
 * v2.1 KG rollback escape hatch. When `CODEWIKI_DISABLE_KG=1`, `find_neighbors`
 * is NOT registered AND the indexer coerces `buildGraph: false` regardless of
 * caller opts. Read once at module load — restart-required to toggle.
 */
const KG_DISABLED = process.env.CODEWIKI_DISABLE_KG === '1';

/**
 * Server version derived from `package.json` at module load (PSF-001 fix).
 * Previously a hardcoded literal here drifted from `package.json.version`,
 * so the MCP server advertised a different version to clients than the
 * npm-installed binary actually was. The runtime read keeps both surfaces
 * synchronized automatically.
 *
 * The resolved path: in dev (tsx) the module is `src/server.ts`, so
 * `../package.json` resolves to the project root. After `tsc` build the
 * module is `dist/server.js`, and `../package.json` again resolves to the
 * project root (since `dist/` is one level below the root).
 */
function loadServerVersion(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const pkgPath = path.resolve(here, '..', 'package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')) as { version?: string };
  if (!pkg.version) {
    throw new Error(`server.ts: failed to read version from ${pkgPath}`);
  }
  return pkg.version;
}

export const SERVER_VERSION = loadServerVersion();

export const SERVER_INSTRUCTIONS =
  'When starting work in a new project, call list_project_dependencies. For semantic ' +
  "retrieval over a dependency's docs, call find_chunks. For graph traversal across " +
  'pages, files, diagrams, and dep cross-references, call find_neighbors. For ' +
  'deterministic navigation by slug, call list_pages then get_page (use `subsection` ' +
  'for deep navigation). Use request_indexing to pre-warm an index before find_chunks. ' +
  'Always surface citation URLs. Content is AI-generated by ' +
  'Google CodeWiki — verify against the source repository for correctness.';

export interface BuildServerOptions {
  cwd: string;
  cache?: Cache;
  client?: CodeWikiClient;
  /** Optional v2 RAG dependencies. Tests inject mocks; production uses defaults. */
  embedder?: Embedder;
  /** v2.6: cross-encoder reranker. Tests inject mocks; production uses the singleton. */
  reranker?: Reranker;
  retriever?: Retriever;
  /** Optional v2.1 KG dependencies. */
  graphQuery?: GraphQuery;
  /** Optional callback returning the project scan, used by find_neighbors `cross_repo` for dep_link derivation. */
  getProjectDeps?: () => ProjectScan;
}

export interface BuiltServer {
  server: McpServer;
  cache: Cache;
  client: CodeWikiClient;
  retriever: Retriever;
  graphQuery: GraphQuery;
  /** v2.8: surfaced so the prewarmer wires onto the SAME Indexer instance the tools use (single-flight collapse). */
  indexer: Indexer;
  toolNames: string[];
}

export async function buildServer(opts: BuildServerOptions): Promise<BuiltServer> {
  const cache = opts.cache ?? (await Cache.open());
  const client = opts.client ?? (await getCodeWikiClient());

  // v2 RAG wiring — lazy: embedder is only loaded when find_chunks is called.
  const embedder = opts.embedder ?? (await getEmbedder());
  // v2.6: reranker singleton (also lazy — model load fires on first score()).
  const reranker = opts.reranker ?? (await getReranker());
  const store = new VectorStore(cache);
  const graphStore = new GraphStore(cache);
  const indexer = new Indexer({ client, embedder, store, graphStore, cache });
  const retriever = opts.retriever ?? new Retriever({ embedder, reranker, store, indexer, cache });
  // v2.5: pass embedder so find_neighbors can lazy-load it for the
  // optional `query` semantic-rank branch. The embedder constructor is
  // free; the encode() lazy-load only fires when query is actually set.
  const graphQuery = opts.graphQuery ?? new GraphQuery({ graphStore, vectorStore: store, cache, indexer, embedder });

  const server = new McpServer(
    { name: 'codewiki-mcp', version: SERVER_VERSION },
    { capabilities: { logging: {} }, instructions: SERVER_INSTRUCTIONS },
  );

  registerListProjectDependencies(server, { cache, client, cwd: opts.cwd });
  registerResolveRepo(server, { cache });
  registerListPages(server, { client });
  registerGetPage(server, { client });
  registerFindChunks(server, { retriever });

  // v2.1 KG: register find_neighbors unless the rollback flag is set.
  if (!KG_DISABLED) {
    registerFindNeighbors(server, { graphQuery, getProjectDeps: opts.getProjectDeps });
  }

  // v2.6: register the 7th tool — request_indexing. First non-readonly tool;
  // NOT gated by KG_DISABLED (works against either chunks-only or full builds).
  registerRequestIndexing(server, { indexer });

  // Tool-surface audit (v2.6): the Cloudmeru-parity regex
  // (search/ask/query/generate/index/write) stays as the guard. ONLY
  // `request_indexing` is whitelisted; all other names still pass the regex
  // check. find_chunks / find_neighbors do NOT match the regex. Test in
  // tests/unit/server.test.ts asserts the whitelist is exactly the
  // single-name frozen set.
  const toolNames = [
    'list_project_dependencies',
    'resolve_repo',
    'list_pages',
    'get_page',
    'find_chunks',
    ...(KG_DISABLED ? [] : ['find_neighbors']),
    'request_indexing',
  ];
  return { server, cache, client, retriever, graphQuery, indexer, toolNames };
}
